// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:medicine_reminder/model/date_item.dart';
import 'package:medicine_reminder/model/med_intake.dart';
import 'package:medicine_reminder/model/med_item.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DateItemAdapter());
    registerAdapter(DayFulfillmentAdapter());
    registerAdapter(DosageTypeAdapter());
    registerAdapter(MedIntakeAdapter());
    registerAdapter(MedItemAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DateItemAdapter());
    registerAdapter(DayFulfillmentAdapter());
    registerAdapter(DosageTypeAdapter());
    registerAdapter(MedIntakeAdapter());
    registerAdapter(MedItemAdapter());
  }
}
